image: Ubuntu2204

environment:
  GIT_USER: "AppVeyor"
  GIT_PASS:
    secure: zhwEyed+swVmmA5wfoORHAVd2uU5USSKgphUnxEu/2ldbMUuvmyRttlaYfTClf8o

install:
  - npm install

build_script:
  - chmod +x ./node_modules/.bin/webpack
  - npx webpack --mode production

test_script:
  - chmod +x ./node_modules/.bin/jest
  - npx jest

deploy_script:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "AppVeyor Bot"
  - npx gh-pages -d dist -r https://$GIT_USER:$GIT_PASS@github.com/TatiMarksman/dom-game.git
