image: Ubuntu2204

environment:
  GITHUB_TOKEN:
    secure: your_encrypted_token_here

install:
  - npm install

build_script:
  - chmod +x ./node_modules/.bin/webpack
  - npx webpack --mode production

test_script:
  - chmod +x ./node_modules/.bin/jest
  - npx jest

artifacts:
  - path: dist

deploy_script:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "AppVeyor Bot"
  - echo "https://${GITHUB_TOKEN}@github.com" > ~/.git-credentials
  - npx gh-pages -d dist
