image: Ubuntu2204

environment:
  GITHUB_TOKEN:
    secure: your_encrypted_token_here

install:
  - npm install

build_script:
  - chmod +x ./node_modules/.bin/webpack
  - npx webpack --mode production


test_script:
  - npm test

artifacts:
  - path: dist

deploy:
  provider: GitHubPages
  artifact: dist
  auth_token:
    secure: zhwEyed+swVmmA5wfoORHAVd2uU5USSKgphUnxEu/2ldbMUuvmyRttlaYfTClf8o
  on:
    branch: main
